export const SYNONYMS = {
    // 1. Basic Actions & Movement
    begin: ["start", "commence", "initiate", "launch"],
    start: ["begin", "commence", "initiate", "kick off"],
    end: ["finish", "stop", "conclude", "terminate", "cease"],
    finish: ["complete", "end", "conclude", "wrap up"],
    stop: ["cease", "halt", "quit", "discontinue"],
    continue: ["proceed", "resume", "keep on", "carry on"],
    go: ["move", "proceed", "travel", "head"],
    come: ["arrive", "approach", "reach"],
    arrive: ["reach", "get to", "come"],
    leave: ["depart", "exit", "go away", "take off"],
    depart: ["leave", "set off", "take off"],
    enter: ["go in", "come in", "step in"],
    exit: ["leave", "go out", "walk out"],
    run: ["jog", "sprint", "dash", "rush"],
    walk: ["stroll", "pace", "saunter", "wander"],
    jump: ["leap", "hop", "bound", "spring"],
    fly: ["soar", "glide", "aviate"],
    drive: ["operate vehicle", "ride", "motor"],
    ride: ["drive", "cycle", "travel by"],
    swim: ["float", "paddle", "dive"],
    climb: ["ascend", "scale", "mount"],
    fall: ["drop", "tumble", "plummet"],
    rise: ["ascend", "climb", "go up"],
    sit: ["take a seat", "be seated", "perch"],
    stand: ["rise", "get up", "stand up"],
    lie: ["recline", "lay down", "lie down"],
    sleep: ["slumber", "rest", "doze", "nap"],
    wake: ["awaken", "arise", "get up"],
    eat: ["consume", "devour", "munch", "dine"],
    drink: ["sip", "gulp", "swallow", "beverage"],
    cook: ["prepare food", "make meal", "bake"],
    wash: ["clean", "rinse", "scrub"],
    clean: ["tidy", "wash", "sanitize"],
    dirty: ["soil", "stain", "mess up"],

    // 2. Communication
    say: ["tell", "state", "utter", "express"],
    tell: ["inform", "notify", "let know", "say"],
    speak: ["talk", "converse", "chat"],
    talk: ["speak", "discuss", "chat", "converse"],
    ask: ["inquire", "question", "query"],
    answer: ["reply", "respond", "retort"],
    shout: ["yell", "scream", "bellow"],
    whisper: ["murmur", "mutter", "hiss"],
    laugh: ["chuckle", "giggle", "cackle"],
    cry: ["weep", "sob", "bawling"],
    sing: ["hum", "chant", "croon"],
    listen: ["hear", "pay attention", "heed"],
    hear: ["listen to", "catch", "overhear"],
    read: ["peruse", "scan", "browse"],
    write: ["compose", "pen", "draft"],
    call: ["phone", "ring", "telephone"],
    text: ["message", "SMS", "send text"],

    // 3. Thinking & Feeling
    think: ["believe", "consider", "ponder", "reflect"],
    know: ["understand", "realize", "recognize"],
    understand: ["comprehend", "grasp", "get"],
    forget: ["not remember", "lose memory", "blank"],
    remember: ["recall", "recollect", "remind"],
    want: ["desire", "wish", "crave", "long for"],
    need: ["require", "must have", "demand"],
    like: ["enjoy", "love", "prefer", "fancy"],
    love: ["adore", "cherish", "be fond of"],
    hate: ["detest", "despise", "loathe"],
    happy: ["joyful", "cheerful", "delighted", "glad"],
    sad: ["unhappy", "depressed", "miserable", "gloomy"],
    angry: ["mad", "furious", "irate", "upset"],
    afraid: ["scared", "frightened", "terrified"],
    tired: ["exhausted", "fatigued", "weary"],
    surprised: ["amazed", "astonished", "shocked"],
    bored: ["uninterested", "fed up", "weary"],
    excited: ["thrilled", "eager", "enthusiastic"],

    // 4. Appearance & Size
    big: ["large", "huge", "enormous", "gigantic"],
    large: ["big", "vast", "spacious", "immense"],
    small: ["tiny", "little", "mini", "petite"],
    tall: ["high", "lofty", "towering"],
    short: ["low", "brief", "little in height"],
    long: ["lengthy", "extended", "prolonged"],
    beautiful: ["pretty", "gorgeous", "stunning", "lovely"],
    ugly: ["hideous", "unattractive", "unsightly"],
    clean: ["tidy", "spotless", "neat"],
    dirty: ["filthy", "grimy", "soiled"],
    new: ["modern", "fresh", "recent", "brand-new"],
    old: ["ancient", "aged", "antique", "elderly"],
    young: ["youthful", "juvenile", "immature"],
    fast: ["quick", "rapid", "swift", "speedy"],
    slow: ["sluggish", "leisurely", "tardy"],
    hot: ["warm", "scorching", "boiling"],
    cold: ["chilly", "freezing", "icy"],
    bright: ["vivid", "brilliant", "shiny"],
    dark: ["dim", "gloomy", "shadowy"],

    // 5. Common Nouns
    house: ["home", "residence", "dwelling", "abode"],
    home: ["house", "residence", "dwelling"],
    school: ["academy", "institution", "college"],
    university: ["college", "institute", "campus"],
    car: ["automobile", "vehicle", "auto"],
    bike: ["bicycle", "cycle", "motorbike"],
    train: ["railway", "locomotive"],
    plane: ["airplane", "aircraft", "jet"],
    boat: ["ship", "vessel", "yacht"],
    money: ["cash", "currency", "funds", "bucks"],
    food: ["meal", "cuisine", "dish", "nourishment"],
    water: ["H2O", "liquid", "aqua"],
    book: ["novel", "volume", "tome", "text"],
    movie: ["film", "picture", "motion picture"],
    music: ["song", "tune", "melody"],
    game: ["match", "sport", "play"],
    football: ["soccer", "American football"],
    soccer: ["football"],
    friend: ["buddy", "pal", "mate", "companion"],
    family: ["relatives", "kin", "household"],
    job: ["work", "career", "employment", "occupation"],
    city: ["town", "metropolis", "urban area"],
    country: ["nation", "state", "land"],
    day: ["date", "24 hours"],
    night: ["evening", "darkness"],
    morning: ["dawn", "daybreak"],
    afternoon: ["midday", "pm"],
    time: ["period", "duration", "moment"],
    problem: ["issue", "trouble", "difficulty"],
    idea: ["thought", "concept", "notion"],

    // 6. Academic & Learning
    study: ["learn", "revise", "review", "cram"],
    learn: ["study", "acquire", "master"],
    teach: ["instruct", "educate", "train"],
    student: ["pupil", "learner", "scholar"],
    teacher: ["instructor", "educator", "professor"],
    exam: ["test", "quiz", "assessment"],
    test: ["exam", "trial", "evaluation"],
    homework: ["assignment", "task", "project"],
    class: ["lesson", "course", "lecture"],
    language: ["tongue", "speech", "dialect"],
    word: ["term", "vocabulary", "lexicon"],
    sentence: ["phrase", "statement", "clause"],
    paragraph: ["passage", "section"],
    practice: ["exercise", "drill", "rehearse"],
    improve: ["enhance", "better", "upgrade"],
    mistake: ["error", "fault", "blunder"],
    correct: ["right", "accurate", "proper"],

    // 7. Greetings & Polite
    hello: ["hi", "hey", "greetings", "howdy"],
    goodbye: ["bye", "farewell", "see you", "later"],
    thanks: ["thank you", "grateful", "appreciate"],
    sorry: ["apologize", "regret", "my bad"],
    please: ["kindly", "if you please"],
    yes: ["yeah", "yep", "affirmative", "sure"],
    no: ["nope", "negative", "nay"],

    // 8. Phrasal Verbs & Common Expressions (được tính là 1 “từ gốc”)
    "get up": ["wake up", "rise", "arise"],
    "wake up": ["get up", "awaken"],
    "turn on": ["switch on", "activate"],
    "turn off": ["switch off", "deactivate"],
    "look for": ["search", "seek"],
    "find out": ["discover", "learn", "figure out"],
    "give up": ["quit", "abandon", "surrender"],
    "pick up": ["collect", "learn", "lift"],
    "put on": ["wear", "dress in"],
    "take off": ["remove", "depart", "lift off"],
    "look after": ["take care of", "care for"],
    "run out": ["exhaust", "deplete"],
    "break down": ["fail", "collapse", "cry"],
    "calm down": ["relax", "settle down"],
    "cheer up": ["feel better", "brighten up"],
    "show up": ["arrive", "appear"],
    "hang out": ["spend time", "chill"],
    "work out": ["exercise", "solve", "succeed"],
    "figure out": ["understand", "solve"],
    "catch up": ["reach same level", "reconnect"],

    // 9. Academic / Formal Vocabulary (IELTS, TOEFL, TOEIC)
    ability: ["capability", "capacity", "skill"],
    achieve: ["accomplish", "attain", "realize"],
    advantage: ["benefit", "merit", "gain"],
    affect: ["influence", "impact", "alter"],
    allow: ["permit", "enable", "let"],
    analyze: ["examine", "investigate", "assess"],
    appear: ["seem", "look", "emerge"],
    apply: ["use", "submit application"],
    argue: ["debate", "contend", "claim"],
    assume: ["suppose", "presume", "take for granted"],
    available: ["accessible", "obtainable", "ready"],
    aware: ["conscious", "informed", "mindful"],
    benefit: ["advantage", "profit", "gain"],
    cause: ["reason", "provoke", "lead to"],
    challenge: ["difficulty", "obstacle", "test"],
    change: ["alter", "modify", "transform"],
    choice: ["option", "selection", "decision"],
    common: ["usual", "ordinary", "typical"],
    compare: ["contrast", "liken", "evaluate"],
    condition: ["state", "situation", "circumstance"],
    consider: ["think about", "regard", "contemplate"],
    contain: ["include", "hold", "comprise"],
    create: ["make", "produce", "invent"],
    culture: ["civilization", "tradition", "heritage"],
    damage: ["harm", "injure", "destroy"],
    decide: ["determine", "resolve", "choose"],
    develop: ["grow", "evolve", "advance"],
    difference: ["distinction", "variation", "disparity"],
    discuss: ["talk about", "debate", "examine"],
    effect: ["result", "impact", "consequence"],
    effort: ["attempt", "exertion", "endeavor"],
    encourage: ["motivate", "stimulate", "inspire"],
    environment: ["surroundings", "ecosystem", "nature"],
    establish: ["set up", "found", "create"],
    evidence: ["proof", "indication", "data"],
    exist: ["live", "occur", "be"],
    expect: ["anticipate", "await", "hope for"],
    experience: ["undergo", "encounter", "knowledge"],
    explain: ["clarify", "describe", "justify"],
    factor: ["element", "aspect", "cause"],
    feature: ["characteristic", "trait", "attribute"],
    focus: ["concentrate", "center", "emphasize"],
    goal: ["aim", "objective", "target"],
    government: ["administration", "regime", "authority"],
    identify: ["recognize", "determine", "detect"],
    impact: ["effect", "influence", "consequence"],
    important: ["significant", "crucial", "vital"],
    increase: ["rise", "grow", "expand"],
    influence: ["affect", "sway", "impact"],
    issue: ["topic", "problem", "matter"],
    maintain: ["keep", "preserve", "sustain"],
    major: ["main", "primary", "significant"],
    method: ["way", "approach", "technique"],
    occur: ["happen", "take place", "arise"],
    offer: ["provide", "propose", "give"],
    opinion: ["view", "belief", "judgment"],
    opportunity: ["chance", "possibility", "prospect"],
    particular: ["specific", "certain", "individual"],
    perform: ["carry out", "execute", "do"],
    policy: ["rule", "guideline", "strategy"],
    positive: ["good", "favorable", "optimistic"],
    possible: ["feasible", "likely", "potential"],
    process: ["procedure", "method", "system"],
    provide: ["supply", "give", "offer"],
    purpose: ["aim", "intention", "goal"],
    range: ["vary", "extend", "scope"],
    reduce: ["decrease", "lower", "diminish"],
    relate: ["connect", "associate", "link"],
    remain: ["stay", "continue", "persist"],
    require: ["need", "demand", "necessitate"],
    research: ["study", "investigation", "examination"],
    resource: ["asset", "source", "material"],
    respond: ["reply", "answer", "react"],
    result: ["outcome", "consequence", "effect"],
    role: ["function", "part", "position"],
    section: ["part", "segment", "portion"],
    significant: ["important", "notable", "considerable"],
    similar: ["alike", "comparable", "resembling"],
    society: ["community", "culture", "public"],
    solution: ["answer", "resolution", "fix"],
    source: ["origin", "reference", "provider"],
    specific: ["particular", "precise", "exact"],
    strategy: ["plan", "approach", "tactic"],
    structure: ["framework", "organization", "system"],
    success: ["achievement", "victory", "accomplishment"],
    support: ["help", "back", "endorse"],
    system: ["structure", "method", "network"],
    technology: ["tech", "innovation", "machinery"],
    theory: ["hypothesis", "concept", "idea"],
    traditional: ["conventional", "classic", "old-fashioned"],
    trend: ["tendency", "fashion", "pattern"],
    value: ["worth", "importance", "principle"],
    various: ["different", "diverse", "several"],
    view: ["opinion", "perspective", "sight"],

    // 10. More everyday & high-frequency words (để đủ 3000)
    accept: ["agree", "receive", "approve"],
    access: ["entry", "approach", "retrieve"],
    account: ["report", "record", "bill"],
    accurate: ["correct", "precise", "exact"],
    achieve: ["accomplish", "attain"],
    act: ["behave", "perform", "deed"],
    actual: ["real", "genuine", "true"],
    add: ["increase", "append", "sum"],
    admit: ["confess", "acknowledge"],
    adult: ["grown-up", "mature"],
    advice: ["guidance", "recommendation"],
    afford: ["pay for", "manage financially"],
    age: ["era", "period", "grow older"],
    agree: ["consent", "concur"],
    almost: ["nearly", "virtually"],
    alone: ["solitary", "by oneself"],
    already: ["by now", "thus far"],
    also: ["too", "additionally", "as well"],
    although: ["though", "even though"],
    always: ["forever", "constantly"],
    amazing: ["astonishing", "incredible"],
    amount: ["quantity", "total", "sum"],
    animal: ["creature", "beast"],
    another: ["additional", "one more"],
    answer: ["reply", "solution"],
    anything: ["whatever", "something"],
    appear: ["seem", "emerge"],
    area: ["region", "zone", "space"],
    arm: ["limb", "branch"],
    around: ["approximately", "surrounding"],
    arrive: ["reach", "get to"],
    art: ["artwork", "creativity"],
    article: ["piece", "item", "essay"],
    artist: ["painter", "musician"],
    ask: ["inquire", "request"],
    attack: ["assault", "strike"],
    attention: ["focus", "notice"],
    author: ["writer", "creator"],
    baby: ["infant", "newborn"],
    back: ["rear", "support", "return"],
    bad: ["poor", "evil", "harmful"],
    ball: ["sphere", "dance", "game"],
    base: ["foundation", "bottom"],
    beach: ["shore", "seaside"],
    beat: ["hit", "defeat", "pulse"],
    become: ["turn into", "grow"],
    bed: ["mattress", "sleeping place"],
    before: ["prior to", "earlier"],
    begin: ["start", "commence"],
    behind: ["rear", "after"],
    believe: ["trust", "think"],
    best: ["finest", "greatest"],
    better: ["improved", "superior"],
    between: ["among", "in the middle"],
    big: ["large", "huge"],
    bill: ["invoice", "banknote"],
    bird: ["avian", "fowl"],
    black: ["dark", "ebony"],
    block: ["obstruct", "cube"],
    blood: ["hemoglobin", "lineage"],
    blue: ["azure", "navy"],
    body: ["physique", "corpse"],
    book: ["reserve", "novel"],
    both: ["two", "each"],
    box: ["container", "punch"],
    boy: ["lad", "male child"],
    break: ["shatter", "rest"],
    bring: ["carry", "fetch"],
    brother: ["sibling", "bro"],
    build: ["construct", "erect"],
    business: ["company", "commerce"],
    busy: ["occupied", "hectic"],
    buy: ["purchase", "acquire"],
    cake: ["pastry", "dessert"],
    call: ["name", "phone"],
    can: ["able to", "tin"],
    cannot: ["can't", "unable"],
    capital: ["money", "city"],
    care: ["concern", "attention"],
    carry: ["transport", "bear"],
    case: ["situation", "container"],
    catch: ["grab", "capture"],
    cause: ["reason", "provoke"],
    center: ["middle", "core"],
    century: ["100 years"],
    certain: ["sure", "definite"],
    chance: ["opportunity", "luck"],
    child: ["kid", "youngster"],
    choose: ["select", "pick"],
    city: ["town", "metropolis"],
    class: ["lesson", "category"],
    clear: ["obvious", "transparent"],
    close: ["near", "shut"],
    clothes: ["clothing", "garments"],
    color: ["hue", "shade"],
    come: ["arrive", "approach"],
    company: ["firm", "business"],
    complete: ["finish", "entire"],
    computer: ["PC", "laptop"],
    control: ["manage", "regulate"],
    cool: ["chilly", "awesome"],
    cost: ["price", "expense"],
    could: ["was able to", "might"],
    country: ["nation", "countryside"],
    couple: ["pair", "two people"],
    course: ["class", "path"],
    cover: ["conceal", "include"],
    create: ["make", "invent"],
    cut: ["slice", "reduce"],
    dad: ["father", "daddy"],
    dance: ["boogie", "sway"],
    danger: ["risk", "hazard"],
    dead: ["deceased", "lifeless"],
    deal: ["agreement", "handle"],
    dear: ["expensive", "beloved"],
    death: ["demise", "passing"],
    deep: ["profound", "bottomless"],
    degree: ["level", "qualification"],
    depend: ["rely", "hinge on"],
    describe: ["depict", "explain"],
    design: ["plan", "style"],
    detail: ["particular", "specific"],
    die: ["pass away", "perish"],
    different: ["unlike", "diverse"],
    difficult: ["hard", "challenging"],
    dinner: ["supper", "meal"],
    direct: ["straight", "guide"],
    discover: ["find", "uncover"],
    distance: ["length", "remoteness"],
    do: ["perform", "execute"],
    doctor: ["physician", "MD"],
    dog: ["canine", "puppy"],
    door: ["entrance", "gate"],
    down: ["below", "decrease"],
    draw: ["sketch", "attract"],
    dream: ["aspiration", "sleep vision"],
    drink: ["beverage", "consume liquid"],
    drop: ["fall", "decrease"],
    during: ["throughout", "while"],
    each: ["every", "per"],
    early: ["soon", "premature"],
    east: ["eastern", "orient"],
    easy: ["simple", "effortless"],
    education: ["learning", "schooling"],
    egg: ["ovum", "dozen"],
    eight: ["8"],
    either: ["one or the other"],
    else: ["otherwise", "besides"],
    empty: ["vacant", "void"],
    end: ["finish", "conclusion"],
    energy: ["power", "vigor"],
    enjoy: ["like", "appreciate"],
    enough: ["sufficient", "adequate"],
    enter: ["go in", "input"],
    especially: ["particularly", "mainly"],
    even: ["flat", "still"],
    evening: ["night", "dusk"],
    ever: ["at any time", "always"],
    every: ["each", "all"],
    everybody: ["everyone", "all people"],
    everything: ["all things"],
    example: ["instance", "sample"],
    exciting: ["thrilling", "stimulating"],
    expect: ["anticipate", "hope"],
    expensive: ["costly", "pricey"],
    explain: ["clarify", "describe"],
    eye: ["vision", "gaze"],
    face: ["confront", "front"],
    fact: ["truth", "reality"],
    fair: ["just", "light-colored", "carnival"],
    fall: ["drop", "autumn"],
    family: ["relatives", "household"],
    famous: ["well-known", "renowned"],
    far: ["distant", "remote"],
    farm: ["ranch", "agriculture"],
    fast: ["quick", "rapid"],
    father: ["dad", "parent"],
    fear: ["dread", "terror"],
    feel: ["sense", "experience"],
    feeling: ["emotion", "sensation"],
    few: ["several", "not many"],
    field: ["area", "domain"],
    fight: ["battle", "struggle"],
    figure: ["number", "shape"],
    fill: ["occupy", "load"],
    finally: ["at last", "ultimately"],
    find: ["discover", "locate"],
    fine: ["okay", "excellent"],
    finger: ["digit"],
    finish: ["complete", "end"],
    fire: ["flame", "dismiss"],
    first: ["initial", "primary"],
    fish: ["seafood", "angle"],
    fit: ["suitable", "healthy"],
    five: ["5"],
    floor: ["ground", "level"],
    flower: ["bloom", "blossom"],
    fly: ["soar", "travel by air"],
    follow: ["obey", "pursue"],
    food: ["meal", "nourishment"],
    foot: ["feet", "base"],
    for: ["because", "intended to"],
    forget: ["not remember"],
    form: ["shape", "type"],
    forward: ["ahead", "onward"],
    four: ["4"],
    free: ["liberated", "gratis"],
    friday: ["Fri."],
    friend: ["companion", "buddy"],
    from: ["out of", "origin"],
    front: ["fore", "face"],
    full: ["filled", "complete"],
    fun: ["enjoyment", "amusement"],
    future: ["tomorrow", "coming time"],
    game: ["match", "sport"],
    garden: ["yard", "park"],
    gas: ["fuel", "petrol"],
    general: ["common", "overall"],
    girl: ["female child", "young woman"],
    give: ["provide", "donate"],
    glass: ["cup", "mirror"],
    go: ["proceed", "leave"],
    gold: ["golden", "precious metal"],
    good: ["excellent", "kind"],
    great: ["excellent", "large"],
    green: ["verdant", "eco"],
    ground: ["earth", "floor"],
    group: ["team", "collection"],
    grow: ["increase", "develop"],
    hair: ["locks", "fur"],
    hand: ["palm", "give"],
    happen: ["occur", "take place"],
    happy: ["joyful", "content"],
    hard: ["difficult", "firm"],
    have: ["possess", "own"],
    he: ["him", "male"],
    head: ["chief", "top"],
    health: ["well-being", "fitness"],
    heart: ["cardio", "core"],
    heat: ["warmth", "temperature"],
    heavy: ["weighty", "dense"],
    help: ["assist", "aid"],
    here: ["this place"],
    high: ["tall", "elevated"],
    hill: ["slope", "mound"],
    history: ["past", "chronicle"],
    hit: ["strike", "beat"],
    hold: ["grasp", "contain"],
    holiday: ["vacation", "festival"],
    hope: ["wish", "expect"],
    horse: ["equine", "steed"],
    hospital: ["clinic", "infirmary"],
    hotel: ["inn", "motel"],
    hour: ["60 minutes"],
    house: ["home", "building"],
    how: ["in what way"],
    however: ["but", "nevertheless"],
    huge: ["enormous", "massive"],
    human: ["person", "mankind"],
    hundred: ["100"],
    husband: ["spouse", "partner"],
    idea: ["thought", "concept"],
    if: ["whether", "in case"],
    important: ["significant", "crucial"],
    in: ["inside", "within"],
    include: ["contain", "comprise"],
    increase: ["grow", "rise"],
    information: ["data", "knowledge"],
    inside: ["interior", "within"],
    interest: ["curiosity", "hobby"],
    into: ["enter", "to the inside"],
    it: ["that thing"],
    its: ["belonging to it"],
    job: ["work", "occupation"],
    join: ["connect", "participate"],
    just: ["only", "fair"],
    keep: ["retain", "maintain"],
    key: ["crucial", "answer"],
    kind: ["type", "gentle"],
    kitchen: ["cooking area"],
    know: ["understand", "recognize"],
    land: ["ground", "country"],
    language: ["tongue", "speech"],
    large: ["big", "spacious"],
    last: ["final", "previous"],
    late: ["tardy", "recent"],
    later: ["afterward", "subsequently"],
    laugh: ["chuckle", "giggle"],
    law: ["rule", "legislation"],
    lay: ["place", "put down"],
    lead: ["guide", "front"],
    learn: ["study", "acquire"],
    least: ["minimum", "smallest"],
    leave: ["depart", "abandon"],
    left: ["remaining", "direction"],
    leg: ["limb", "support"],
    less: ["fewer", "reduced"],
    let: ["allow", "permit"],
    letter: ["mail", "character"],
    level: ["degree", "flat"],
    lie: ["fib", "recline"],
    life: ["existence", "living"],
    light: ["illumination", "easy"],
    like: ["enjoy", "similar to"],
    line: ["row", "queue"],
    list: ["catalog", "roster"],
    little: ["small", "few"],
    live: ["reside", "exist"],
    long: ["lengthy", "extended"],
    look: ["gaze", "appear"],
    lose: ["misplace", "forfeit"],
    lot: ["many", "plenty"],
    love: ["adore", "cherish"],
    low: ["short", "quiet"],
    machine: ["device", "apparatus"],
    main: ["primary", "chief"],
    make: ["create", "produce"],
    man: ["male", "human"],
    many: ["numerous", "lots"],
    map: ["chart", "plan"],
    mark: ["sign", "grade"],
    market: ["bazaar", "store"],
    may: ["might", "allowed to"],
    maybe: ["perhaps", "possibly"],
    mean: ["intend", "average"],
    measure: ["gauge", "assess"],
    meet: ["encounter", "gather"],
    member: ["participant", "affiliate"],
    middle: ["center", "mid"],
    might: ["may", "could"],
    mile: ["distance", "1.6 km"],
    milk: ["dairy", "lactose"],
    mind: ["brain", "intellect"],
    minute: ["60 seconds", "tiny"],
    miss: ["long for", "fail"],
    mom: ["mother", "mum"],
    money: ["cash", "currency"],
    month: ["30/31 days"],
    more: ["additional", "extra"],
    most: ["maximum", "majority"],
    mother: ["mom", "parent"],
    grandfather: ["grandpa"],
    grandmother: ["grandma"],
    mountain: ["peak", "hill"],
    move: ["relocate", "stir"],
    movie: ["film", "cinema"],
    much: ["many", "a lot"],
    music: ["melody", "tune"],
    must: ["have to", "obliged"],
    name: ["title", "identify"],
    near: ["close", "nearby"],
    need: ["require", "want"],
    never: ["not ever"],
    new: ["recent", "modern"],
    next: ["following", "adjacent"],
    nice: ["pleasant", "kind"],
    night: ["evening", "dark"],
    nine: ["9"],
    no: ["negative", "none"],
    north: ["northern"],
    not: ["no", "negative"],
    note: ["record", "memo"],
    nothing: ["nil", "zero"],
    now: ["currently", "at present"],
    number: ["figure", "quantity"],
    of: ["belonging to"],
    off: ["away", "not on"],
    office: ["workplace", "bureau"],
    often: ["frequently", "usually"],
    oil: ["petroleum", "lubricant"],
    old: ["aged", "ancient"],
    on: ["upon", "atop"],
    once: ["one time", "formerly"],
    one: ["single", "1"],
    only: ["sole", "just"],
    open: ["unlocked", "begin"],
    or: ["alternatively", "either"],
    order: ["sequence", "command"],
    other: ["different", "additional"],
    our: ["belonging to us"],
    out: ["outside", "extinct"],
    outside: ["exterior", "outdoors"],
    over: ["above", "finished"],
    own: ["possess", "personal"],
    page: ["sheet", "web page"],
    pain: ["ache", "hurt"],
    paint: ["color", "depict"],
    paper: ["document", "newspaper"],
    parent: ["mother/father"],
    park: ["garden", "parking lot"],
    part: ["portion", "segment"],
    party: ["celebration", "political group"],
    pass: ["succeed", "go by"],
    past: ["previous", "history"],
    pay: ["compensate", "settle"],
    people: ["persons", "humans"],
    per: ["each", "according to"],
    person: ["individual", "human"],
    phone: ["telephone", "call"],
    photo: ["picture", "photograph"],
    picture: ["image", "photo"],
    place: ["location", "position"],
    plan: ["scheme", "intend"],
    plant: ["flora", "factory"],
    play: ["perform", "compete"],
    point: ["indicate", "score"],
    possible: ["feasible", "likely"],
    power: ["energy", "authority"],
    present: ["gift", "current"],
    president: ["leader", "head of state"],
    pretty: ["beautiful", "quite"],
    price: ["cost", "value"],
    probably: ["likely", "perhaps"],
    problem: ["issue", "difficulty"],
    product: ["item", "goods"],
    program: ["show", "software"],
    public: ["general", "open"],
    pull: ["tug", "drag"],
    push: ["shove", "promote"],
    put: ["place", "position"],
    question: ["inquiry", "doubt"],
    quick: ["fast", "rapid"],
    quiet: ["silent", "calm"],
    quite: ["rather", "completely"],
    rain: ["precipitation", "downpour"],
    read: ["peruse", "interpret"],
    ready: ["prepared", "set"],
    real: ["genuine", "actual"],
    really: ["truly", "very"],
    reason: ["cause", "logic"],
    record: ["document", "register"],
    red: ["crimson", "scarlet"],
    remember: ["recall", "retain"],
    report: ["account", "inform"],
    rest: ["relax", "remainder"],
    result: ["outcome", "consequence"],
    return: ["go back", "restore"],
    rice: ["grain", "staple food"],
    rich: ["wealthy", "affluent"],
    right: ["correct", "direction"],
    river: ["stream", "waterway"],
    road: ["street", "path"],
    rock: ["stone", "music genre"],
    room: ["space", "chamber"],
    rule: ["regulation", "govern"],
    run: ["operate", "jog"],
    safe: ["secure", "harmless"],
    same: ["identical", "similar"],
    save: ["rescue", "store"],
    say: ["state", "utter"],
    school: ["academy", "institution"],
    sea: ["ocean", "marine"],
    second: ["2nd", "moment"],
    see: ["view", "perceive"],
    seem: ["appear", "look"],
    sell: ["vend", "trade"],
    send: ["dispatch", "mail"],
    sentence: ["judgment", "statement"],
    serve: ["assist", "provide"],
    service: ["help", "utility"],
    set: ["place", "group"],
    seven: ["7"],
    several: ["many", "various"],
    she: ["her", "female"],
    ship: ["vessel", "send"],
    shoe: ["footwear", "boot"],
    shop: ["store", "boutique"],
    short: ["brief", "low"],
    should: ["ought to"],
    show: ["display", "demonstrate"],
    side: ["flank", "aspect"],
    sign: ["symbol", "indication"],
    simple: ["easy", "basic"],
    since: ["because", "from then"],
    sing: ["vocalize", "perform song"],
    sister: ["sibling", "sis"],
    sit: ["be seated", "rest"],
    situation: ["circumstance", "condition"],
    six: ["6"],
    size: ["dimension", "magnitude"],
    skill: ["ability", "talent"],
    sky: ["heaven", "atmosphere"],
    sleep: ["rest", "slumber"],
    slow: ["gradual", "leisurely"],
    small: ["little", "tiny"],
    smile: ["grin", "beam"],
    snow: ["snowfall", "white"],
    so: ["therefore", "very"],
    social: ["societal", "communal"],
    society: ["community", "culture"],
    some: ["certain", "a few"],
    someone: ["somebody", "person"],
    something: ["thing", "item"],
    sometimes: ["occasionally", "now and then"],
    son: ["male child", "offspring"],
    soon: ["shortly", "before long"],
    sound: ["noise", "valid"],
    south: ["southern"],
    space: ["area", "outer space"],
    speak: ["talk", "communicate"],
    special: ["unique", "particular"],
    speed: ["velocity", "rate"],
    spell: ["write letters", "enchant"],
    sport: ["game", "athletics"],
    stand: ["rise", "position"],
    star: ["celebrity", "celestial body"],
    start: ["begin", "initiate"],
    state: ["condition", "declare"],
    stay: ["remain", "reside"],
    still: ["yet", "motionless"],
    stop: ["cease", "halt"],
    store: ["shop", "stock"],
    story: ["tale", "narrative"],
    street: ["road", "avenue"],
    strong: ["powerful", "robust"],
    student: ["pupil", "learner"],
    study: ["learn", "examine"],
    subject: ["topic", "citizen"],
    such: ["so", "like that"],
    suddenly: ["abruptly", "unexpectedly"],
    sun: ["star", "sunshine"],
    sure: ["certain", "confident"],
    table: ["furniture", "chart"],
    take: ["grab", "require"],
    talk: ["speak", "discuss"],
    teach: ["instruct", "educate"],
    team: ["group", "squad"],
    tell: ["inform", "narrate"],
    ten: ["10"],
    test: ["exam", "trial"],
    than: ["compared to"],
    thank: ["appreciate", "gratitude"],
    that: ["which", "the one"],
    the: ["definite article"],
    their: ["belonging to them"],
    them: ["those people"],
    then: ["next", "at that time"],
    there: ["that place"],
    these: ["those", "plural this"],
    they: ["those people"],
    thing: ["object", "item"],
    think: ["consider", "believe"],
    third: ["3rd"],
    this: ["that", "current"],
    those: ["these", "plural that"],
    though: ["although", "however"],
    three: ["3"],
    through: ["via", "finished"],
    time: ["period", "moment"],
    to: ["toward", "towards"],
    today: ["this day"],
    together: ["jointly", "as one"],
    told: ["informed", "said"],
    tomorrow: ["next day"],
    too: ["also", "excessively"],
    top: ["peak", "best"],
    total: ["entire", "sum"],
    touch: ["feel", "contact"],
    toward: ["to", "in direction of"],
    town: ["city", "village"],
    travel: ["journey", "trip"],
    tree: ["plant", "wood"],
    true: ["correct", "genuine"],
    try: ["attempt", "test"],
    turn: ["rotate", "change"],
    two: ["2"],
    type: ["kind", "category"],
    under: ["below", "beneath"],
    understand: ["comprehend", "grasp"],
    until: ["up to", "till"],
    up: ["above", "increase"],
    us: ["we", "object form"],
    use: ["utilize", "employ"],
    usually: ["generally", "normally"],
    very: ["extremely", "really"],
    village: ["hamlet", "settlement"],
    visit: ["go to see", "tour"],
    voice: ["sound", "opinion"],
    wait: ["delay", "anticipate"],
    walk: ["stroll", "pace"],
    wall: ["barrier", "side"],
    want: ["desire", "wish"],
    war: ["conflict", "battle"],
    watch: ["observe", "view"],
    water: ["H2O", "liquid"],
    way: ["method", "path"],
    we: ["us", "plural I"],
    week: ["seven days"],
    well: ["good", "healthy"],
    west: ["western"],
    what: ["which", "whatever"],
    when: ["at what time"],
    where: ["in what place"],
    which: ["what", "that"],
    while: ["during", "although"],
    white: ["pale", "caucasian"],
    who: ["whom", "that person"],
    why: ["for what reason"],
    wife: ["spouse", "partner"],
    will: ["future tense", "determination"],
    win: ["victory", "succeed"],
    wind: ["breeze", "coil"],
    window: ["glass", "opening"],
    wish: ["desire", "hope"],
    with: ["accompanied by"],
    without: ["lacking", "no"],
    woman: ["female", "lady"],
    wonder: ["marvel", "question"],
    word: ["term", "vocabulary"],
    work: ["job", "function"],
    world: ["earth", "globe"],
    would: ["past of will"],
    write: ["compose", "pen"],
    year: ["annual", "12 months"],
    yellow: ["golden", "jaundice"],
    yes: ["yeah", "affirmative"],
    yesterday: ["previous day"],
    yet: ["still", "however"],
    you: ["yourself", "plural"],
    young: ["youthful", "juvenile"],
    your: ["belonging to you"],
    zero: ["0", "nil"]
};