name: Learning English CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      BACKEND_IMAGE: taidepzai/backend_learningenglish
      FRONTEND_IMAGE: taidepzai/frontend_learningenglish

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js for build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Build & test backend (nếu có test)
      - name: Install backend dependencies
        run: |
          cd apps
          npm ci

      # - name: Run backend tests
      #   run: |
      #     cd apps
      #     npm test
      - name: Skip backend tests
        run: echo "Skipping backend tests (no tests defined yet)"

      # 4️⃣ Build frontend
      - name: Install frontend dependencies
        run: |
          cd webapp
          npm ci

      - name: Build frontend
        run: |
          cd webapp
          npm run build

      # 5️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build & push backend Docker image
      - name: Build & push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps
          file: ./apps/Dockerfile
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

      # 7️⃣ Build & push frontend Docker image
      - name: Build & push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

      # 8️⃣ Deploy lên EC2
      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Decode key và lưu tạm
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2_key.pem
          chmod 600 ec2_key.pem

          ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd ~/EasyTalk_LearningEnglish || exit
            echo "Pull latest Docker images"
            docker pull taidepzai/backend_learningenglish:latest
            docker pull taidepzai/frontend_learningenglish:latest

            echo "Stop current containers if running"
            docker-compose down

            echo "Start containers with new images"
            docker-compose up -d
          EOF